### PR TITLE
Win build + install python bindings on Unix

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Hi @traversaro @wolfv - any clue how to overcome this issue? I think it's something basic but I'm not a Windows expert ..

```
2022-07-28T02:58:21.9878572Z LINK : fatal error LNK1104: cannot open file 'lib\metis-gtsamDebug.lib'
```
Note that prior to that:
```
2022-07-28T02:51:29.6173860Z [62/285] Linking C shared library bin\metis-gtsamDebug.dll
```

So the dll gets created but not the lib.

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
> So the dll gets created but not the lib.

Not sure if you solved the problem, but this tipically happens if no symbols are exported.

**Comment by Tobias-Fischer** [comment]
Thanks @traversaro - oddly enough the issue above was fixed with using vs2019.

After a few more export fixes, the build now fails at nearly the last step. Any idea? 

```
[221/223] Linking CXX shared module python\gtsam_unstable\gtsam_unstable.cp38-win_amd64.pyd
FAILED: python/gtsam_unstable/gtsam_unstable.cp38-win_amd64.pyd 
cmd.exe /C "cd . && %BUILD_PREFIX%\Library\bin\cmake.exe -E vs_link_dll --intdir=python\CMakeFiles\gtsam_unstable_py.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~1\2019\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\link.exe /nologo python\CMakeFiles\gtsam_unstable_py.dir\gtsam_unstable.cpp.obj  /out:python\gtsam_unstable\gtsam_unstable.cp38-win_amd64.pyd /implib:lib\gtsam_unstable.lib /pdb:python\gtsam_unstable\gtsam_unstable.pdb /dll /version:0.0 /machine:x64 /INCREMENTAL:NO  -LTCG  lib\gtsam_unstable.lib  C:\hostedtoolcache\windows\Python\3.8.10\x64\libs\python38.lib  lib\gtsam.lib  %PREFIX%\Library\lib\boost_serialization.lib  %PREFIX%\Library\lib\boost_system.lib  %PREFIX%\Library\lib\boost_filesystem.lib  %PREFIX%\Library\lib\boost_thread.lib  %PREFIX%\Library\lib\boost_atomic.lib  %PREFIX%\Library\lib\boost_date_time.lib  %PREFIX%\Library\lib\boost_regex.lib  %PREFIX%\Library\lib\boost_timer.lib  %PREFIX%\Library\lib\boost_chrono.lib  tbb.lib  tbbmalloc.lib  %PREFIX%\Library\lib\metis.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib  && cd ."
LINK: command "C:\PROGRA~2\MICROS~1\2019\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\link.exe /nologo python\CMakeFiles\gtsam_unstable_py.dir\gtsam_unstable.cpp.obj /out:python\gtsam_unstable\gtsam_unstable.cp38-win_amd64.pyd /implib:lib\gtsam_unstable.lib /pdb:python\gtsam_unstable\gtsam_unstable.pdb /dll /version:0.0 /machine:x64 /INCREMENTAL:NO -LTCG lib\gtsam_unstable.lib C:\hostedtoolcache\windows\Python\3.8.10\x64\libs\python38.lib lib\gtsam.lib %PREFIX%\Library\lib\boost_serialization.lib %PREFIX%\Library\lib\boost_system.lib %PREFIX%\Library\lib\boost_filesystem.lib %PREFIX%\Library\lib\boost_thread.lib %PREFIX%\Library\lib\boost_atomic.lib %PREFIX%\Library\lib\boost_date_time.lib %PREFIX%\Library\lib\boost_regex.lib %PREFIX%\Library\lib\boost_timer.lib %PREFIX%\Library\lib\boost_chrono.lib tbb.lib tbbmalloc.lib %PREFIX%\Library\lib\metis.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:python\gtsam_unstable\gtsam_unstable.cp38-win_amd64.pyd.manifest" failed (exit code 1149) with the following output:
LINK : fatal error LNK1149: output filename matches input filename '%SRC_DIR%\build\lib\gtsam_unstable.lib'
```

The same happens for gtsam.lib

**Comment by Tobias-Fischer** [comment]
Relevant cmake: https://github.com/borglab/gtsam/blob/4.1.1/python/CMakeLists.txt

**Comment by traversaro** [comment]
I think the problem is https://github.com/borglab/gtsam/blob/4.1.1/python/CMakeLists.txt#L86 . We had a similar problem with osqp, if I recall correctly, see https://github.com/tesseract-robotics/trajopt/pull/287 . Basically the problem is that on Linux people rename to the same name different libraries because they have different suffix (like .a vs .so for static vs shared, or .pysomething vs .so for Python vs shared C++). However, on Windows when you build a shared library you create both a name.lib and a name.dll, so if you have a static and shared library with the same name, that results in a collision. Similalry, if you have a `name.dll` and `name.pyd` (C++ and Python), both will also generate a `name.lib` that will result in a collision. Also https://github.com/pantor/ruckig/pull/18 I think may be related.

**Comment by traversaro** [comment]
Yes, looking more in detail https://github.com/pantor/ruckig/pull/18 is exactly the same problem (down to the error message), and so it can provide a possible fix.

**Comment by Tobias-Fischer** [comment]
Awesome, that really helps! Let's see whether the build succeeds now - fingers crossed.

PS: Let me know if you want to become a maintainer here.

**Comment by traversaro** [comment]
> PS: Let me know if you want to become a maintainer here.

Ok!

**Comment by Tobias-Fischer** [comment]
Ah .. another annoying one:
```
[211/223] Building CXX object python\CMakeFiles\gtsam_py.dir\base.cpp.obj
FAILED: python/CMakeFiles/gtsam_py.dir/base.cpp.obj 
C:\PROGRA~2\MICROS~1\2019\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\cl.exe  /nologo /TP -DEIGEN_NO_STATIC_ASSERT -Dgtsam_py_EXPORTS -I%SRC_DIR% -I%SRC_DIR%\build -I%SRC_DIR%\CppUnitLite -I%PREFIX%\Library\include\eigen3 -external:IC:\hostedtoolcache\windows\Python\3.10.5\x64\include -external:I%SRC_DIR%\wrap\pybind11\include -external:I%SRC_DIR%\gtsam\3rdparty\SuiteSparse_config -external:I%SRC_DIR%\gtsam\3rdparty\Spectra -external:I%SRC_DIR%\gtsam\3rdparty\CCOLAMD\Include -external:I%PREFIX%\Library\include -external:W0 /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MD /O2 /Ob2 /DNDEBUG /bigobj /MP /GL /wd4267 /showIncludes /Fopython\CMakeFiles\gtsam_py.dir\base.cpp.obj /Fdpython\CMakeFiles\gtsam_py.dir\ /FS -c %SRC_DIR%\build\python\base.cpp
%SRC_DIR%\wrap\pybind11\include\pybind11\numpy.h(36): error C2065: 'ssize_t': undeclared identifier
%SRC_DIR%\wrap\pybind11\include\pybind11\numpy.h(36): error C2338: ssize_t != Py_intptr_t
```

**Comment by Tobias-Fischer** [comment]
I'm trying without Python and without the gtsam-unstable for now just to see if that succeeds. I also limited the number of cores on the win build, as half the time the compiler went out of heap space.

**Comment by Tobias-Fischer** [comment]
So it seems like the python buildings on Windows are terribly broken, with
```
python\gtsam\gtsam.cp37-win_amd64.pyd : fatal error LNK1120: 105 unresolved externals
```

Just the first few lines of errors:
```

LINK: command "C:\PROGRA~2\MICROS~1\2019\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\link.exe /nologo python\CMakeFiles\gtsam_py.dir\gtsam.cpp.obj python\CMakeFiles\gtsam_py.dir\base.cpp.obj python\CMakeFiles\gtsam_py.dir\geometry.cpp.obj python\CMakeFiles\gtsam_py.dir\linear.cpp.obj python\CMakeFiles\gtsam_py.dir\nonlinear.cpp.obj python\CMakeFiles\gtsam_py.dir\symbolic.cpp.obj python\CMakeFiles\gtsam_py.dir\sam.cpp.obj python\CMakeFiles\gtsam_py.dir\slam.cpp.obj python\CMakeFiles\gtsam_py.dir\sfm.cpp.obj python\CMakeFiles\gtsam_py.dir\navigation.cpp.obj python\CMakeFiles\gtsam_py.dir\basis.cpp.obj /out:python\gtsam\gtsam.cp37-win_amd64.pyd /implib:lib\python_gtsam.lib /pdb:python\gtsam\gtsam.pdb /dll /version:0.0 /machine:x64 /INCREMENTAL:NO -LTCG lib\gtsam.lib C:\hostedtoolcache\windows\Python\3.7.9\x64\libs\python37.lib %PREFIX%\Library\lib\boost_serialization.lib %PREFIX%\Library\lib\boost_system.lib %PREFIX%\Library\lib\boost_filesystem.lib %PREFIX%\Library\lib\boost_thread.lib %PREFIX%\Library\lib\boost_atomic.lib %PREFIX%\Library\lib\boost_date_time.lib %PREFIX%\Library\lib\boost_regex.lib %PREFIX%\Library\lib\boost_timer.lib %PREFIX%\Library\lib\boost_chrono.lib tbb.lib tbbmalloc.lib %PREFIX%\Library\lib\metis.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:python\gtsam\gtsam.cp37-win_amd64.pyd.manifest" failed (exit code 1120) with the following output:
   Creating library lib\python_gtsam.lib and object lib\python_gtsam.exp
geometry.cpp.obj : error LNK2001: unresolved external symbol "public: class Eigen::Matrix<double,-1,1,0,-1,1> __cdecl gtsam::SO<-1>::vec(class gtsam::OptionalJacobian<-1,-1>)const " (?vec@?$SO@$0?0@gtsam@@QEBA?AV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@V?$OptionalJacobian@$0?0$0?0@2@@Z)
nonlinear.cpp.obj : error LNK2001: unresolved external symbol "public: virtual class boost::shared_ptr<class gtsam::NonlinearFactor> __cdecl gtsam::LinearContainerFactor::rekey(class std::map<unsigned __int64,unsigned __int64,struct std::less<unsigned __int64>,class std::allocator<struct std::pair<unsigned __int64 const ,unsigned __int64> > > const &)const " (?rekey@LinearContainerFactor@gtsam@@UEBA?AV?$shared_ptr@VNonlinearFactor@gtsam@@@boost@@AEBV?$map@_K_KU?$less@_K@std@@V?$allocator@U?$pair@$$CB_K_K@std@@@2@@std@@@Z)
nonlinear.cpp.obj : error LNK2001: unresolved external symbol "public: virtual class boost::shared_ptr<class gtsam::NonlinearFactor> __cdecl gtsam::LinearContainerFactor::rekey(class std::vector<unsigned __int64,class tbb::detail::d1::tbb_allocator<unsigned __int64> > const &)const " (?rekey@LinearContainerFactor@gtsam@@UEBA?AV?$shared_ptr@VNonlinearFactor@gtsam@@@boost@@AEBV?$vector@_KV?$tbb_allocator@_K@d1@detail@tbb@@@std@@@Z)
nonlinear.cpp.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl gtsam::CustomFactor::print(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::function<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl(unsigned __int64)> const &)const " (?print@CustomFactor@gtsam@@UEBAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV?$function@$$A6A?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_K@Z@4@@Z)
nonlinear.cpp.obj : error LNK2001: unresolved external symbol "public: virtual class Eigen::Matrix<double,-1,1,0,-1,1> __cdecl gtsam::CustomFactor::unwhitenedError(class gtsam::Values const &,class boost::optional<class std::vector<class Eigen::Matrix<double,-1,-1,0,-1,-1>,class std::allocator<class Eigen::Matrix<double,-1,-1,0,-1,-1> > > &>)const " (?unwhitenedError@CustomFactor@gtsam@@UEBA?AV?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@AEBVValues@2@V?$optional@AEAV?$vector@V?$Matrix@N$0?0$0?0$0A@$0?0$0?0@Eigen@@V?$allocator@V?$Matrix@N$0?0$0?0$0A@$0?0$0?0@Eigen@@@std@@@std@@@boost@@@Z)
slam.cpp.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl gtsam::FrobeniusFactor<class gtsam::SO<3> >::FrobeniusFactor<class gtsam::SO<3> >(unsigned __int64,unsigned __int64,class boost::shared_ptr<class gtsam::noiseModel::Base> const &)" (__imp_??0?$FrobeniusFactor@V?$SO@$02@gtsam@@@gtsam@@QEAA@_K0AEBV?$shared_ptr@VBase@noiseModel@gtsam@@@boost@@@Z)
slam.cpp.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl gtsam::FrobeniusFactor<class gtsam::SO<4> >::FrobeniusFactor<class gtsam::SO<4> >(unsigned __int64,unsigned __int64,class boost::shared_ptr<class gtsam::noiseModel::Base> const &)" (__imp_??0?$FrobeniusFactor@V?$SO@$03@gtsam@@@gtsam@@QEAA@_K0AEBV?$shared_ptr@VBase@noiseModel@gtsam@@@boost@@@Z)
slam.cpp.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl gtsam::FrobeniusBetweenFactor<class gtsam::SO<4> >::FrobeniusBetweenFactor<class gtsam::SO<4> >(unsigned __int64,unsigned __int64,class gtsam::SO<4> const &,class boost::shared_ptr<class gtsam::noiseModel::Base> const &)" (__imp_??0?$FrobeniusBetweenFactor@V?$SO@$03@gtsam@@@gtsam@@QEAA@_K0AEBV?$SO@$03@1@AEBV?$shared_ptr@VBase@noiseModel@gtsam@@@boost@@@Z)
  Hint on symbols that are defined and could potentially match:
    "__declspec(dllimport) public: __cdecl gtsam::FrobeniusBetweenFactor<class gtsam::SO<3> >::FrobeniusBetweenFactor<class gtsam::SO<3> >(unsigned __int64,unsigned __int64,class gtsam::SO<3> const &,class boost::shared_ptr<class gtsam::noiseModel::Base> const &)" (__imp_??0?$FrobeniusBetweenFactor@V?$SO@$02@gtsam@@@gtsam@@QEAA@_K0AEBV?$SO@$02@1@AEBV?$shared_ptr@VBase@noiseModel@gtsam@@@boost@@@Z)
slam.cpp.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual __cdecl gtsam::FrobeniusBetweenFactor<class gtsam::SO<4> >::~FrobeniusBetweenFactor<class gtsam::SO<4> >(void)" (__imp_??1?$FrobeniusBetweenFactor@V?$SO@$03@gtsam@@@gtsam@@UEAA@XZ)
  Hint on symbols that are defined and could potentially match:
    "__declspec(dllimport) public: virtual __cdecl gtsam::FrobeniusBetweenFactor<class gtsam::SO<3> >::~FrobeniusBetweenFactor<class gtsam::SO<3> >(void)" (__imp_??1?$FrobeniusBetweenFactor@V?$SO@$02@gtsam@@@gtsam@@UEAA@XZ)
```

Therefore, I suggest disabling python bindings on Windows for now. We can open an upstream issue to see if they are interested in fixing it?

**Comment by Tobias-Fischer** [comment]
I also noticed that previous builds didn't install the python bindings (they were built but not installed).

On linux-64 everything builds+installs fine, but on osx something goes wrong with the relocations. The python bindings are looking for the libs in the build folder, which don't exist at test time:
```
import: 'gtsam'
Traceback (most recent call last):
  File "/Users/runner/miniforge3/conda-bld/gtsam_1659143045054/test_tmp/run_test.py", line 2, in <module>
    import gtsam
  File "/Users/runner/miniforge3/conda-bld/gtsam_1659143045054/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.8/site-packages/gtsam/__init__.py", line 7, in <module>
    from gtsam import gtsam, utils
ImportError: dlopen(/Users/runner/miniforge3/conda-bld/gtsam_1659143045054/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.8/site-packages/gtsam/gtsam.cpython-38-darwin.so, 2): Library not loaded: /Users/runner/miniforge3/conda-bld/gtsam_1659143045054/work/build/gtsam/libgtsam.4.dylib
  Referenced from: /Users/runner/miniforge3/conda-bld/gtsam_1659143045054/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.8/site-packages/gtsam/gtsam.cpython-38-darwin.so
  Reason: image not found
```

Also see related warnings:
```
WARNING (gtsam,lib/python3.8/site-packages/gtsam_unstable/gtsam_unstable.cpython-38-darwin.so): /Users/runner/miniforge3/conda-bld/gtsam_1659143045054/work/build/gtsam_unstable/libgtsam_unstable.4.dylib not found in packages, sysroot(s) nor the missing_dso_whitelist.
.. is this binary repackaging?
WARNING (gtsam,lib/python3.8/site-packages/gtsam_unstable/gtsam_unstable.cpython-38-darwin.so): /Users/runner/miniforge3/conda-bld/gtsam_1659143045054/work/build/gtsam/libgtsam.4.dylib not found in packages, sysroot(s) nor the missing_dso_whitelist.
.. is this binary repackaging?
...
WARNING (gtsam,lib/python3.8/site-packages/gtsam/gtsam.cpython-38-darwin.so): /Users/runner/miniforge3/conda-bld/gtsam_1659143045054/work/build/gtsam/libgtsam.4.dylib not found in packages, sysroot(s) nor the missing_dso_whitelist.
.. is this binary repackaging?
```

Any ideas how to resolve this @wolfv @traversaro? Weird that it works on linux but not osx.

**Comment by Tobias-Fischer** [comment]
I fixed above error by setting CMAKE_SKIP_RPATH=TRUE

In this case conda-build is smart enough to do a proper relocation. However this does not happen till the packaging step, so I'm skipping ninja check on osx for now.

I think this is ready to go, unless there are any objections?

The only missing bit are the windows python bindings - I'll open an upstream issue. I'll also try and get some patches upstreamed.

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
I created some PRs / issues in gtsam upstream: 
- Allowing system ceres: https://github.com/borglab/gtsam/issues/1259
- Fix exports on Win: https://github.com/borglab/gtsam/pull/1257
- Metis linking fix: https://github.com/borglab/gtsam/pull/1258
- Remove old version of FindBoost.cmake: https://github.com/borglab/gtsam/pull/1260

**Pull request merged**
